### ISSUE TITLE
Schedule column discipline

### ISSUE THREAD

**Issue by jabamula** [smart-underworld/seestar_alp#205]
In the schedule window the columns of the top line and the lines of schedule items should be synchronized. If you narrow the window, the items rows cut earlier and the user gets confused.

In the image it looks like the LP filter is true.

The culprit is the coordinates that can't fit the automatic column narrowing. Might be that shortening decimal precision (issue #134) would also help here.

**Comment by erewhon** [comment]
This happened during one of my live streams.   I had a schedule in a window that was half screen and it looked like LP was false, but it was auto focus.  (I think.)

**Comment by jabamula** [comment]
I forgot to insert the image, which shows exactly the same thing you are talking about. It happened to me and I reacted too quick and aborted my mission.

<img width="1041" alt="SSC with uneven columns" src="https://github.com/user-attachments/assets/ff9fdbda-ef4d-4792-9b4c-105f6196c62e">

**Comment by smart-underworld** [comment]
I went ahead and fixed it at the lowest level. All coordinates will have at most 1 decimal precision for seconds.

![Screenshot 2024-09-04 003001](https://github.com/user-attachments/assets/7679c50f-33c7-4aa8-b05b-5354c3277046)

**Comment by smart-underworld** [comment]
fixed with https://github.com/smart-underworld/seestar_alp/commit/318c7fe5f5240de0f73ab278bbf2742ad1312b32

**Comment by jabamula** [comment]
Good, can you check that it also works off-line. I seem to still get more decimals?

**Comment by smart-underworld** [comment]
My code works on the daemon level, so that may explain what you see when
offline

**Comment by YungKC** [comment]
How did you construct the scheduler item that results in long precision
decimals offline? I can try to reproduce.

**Comment by jabamula** [comment]
I searched from Simbad for SS Cyg.

**Comment by jabamula** [comment]
Just also noted that, of course, you can manually remove digits. ;)

**Comment by YungKC** [comment]
Found the issue in SSC. Fixed and merged.
